import { DANFE_WHATSAPP } from './content';
export function mobileHome() {
  return `<section class="mobile-home wrap"><div class="app-greeting"><span class="eyebrow">Your space, taken care of</span><h2>What needs<br>a fresh start?</h2><p>Book cleaning in Sharjah & Dubai.</p></div><div class="city-switch"><a href="/book?city=Sharjah">Sharjah</a><a href="/book?city=Dubai">Dubai</a></div><a class="app-promo" href="/book"><span>LET’S MAKE ROOM FOR YOU</span><strong>Your next clean,<br>just a few taps away.</strong><span>Choose a service & time <span aria-hidden="true">→</span></span></a><div class="app-section-title"><h3>Choose your clean</h3><a href="/book">View all</a></div><div class="app-service-grid" id="app-services"><a href="/book?category=danfe_normal"><span aria-hidden="true">⌂</span><strong>Normal cleaning</strong><small>You provide supplies</small><b data-rate="normal">AED 25 / hour</b></a><a href="/book?category=danfe_materials"><span aria-hidden="true">✦</span><strong>With materials</strong><small>We bring cleaning supplies</small><b data-rate="materials">AED 35 / hour</b></a><a href="/services/deep-cleaning-sharjah"><span aria-hidden="true">◇</span><strong>Deep cleaning</strong><small>Discuss a detailed clean</small><b>Request a quote</b></a><a href="/services/move-in-move-out-cleaning-sharjah"><span aria-hidden="true">▣</span><strong>Moving clean</strong><small>A fresh chapter starts here</small><b>Request a quote</b></a></div><a class="app-booking-link" href="/bookings"><span><strong>Already have a booking?</strong><small>See your latest status and updates</small></span><span aria-hidden="true">→</span></a><div class="app-section-title"><h3>Clean spaces, both cities</h3></div><div class="city-cards"><a href="/cleaning-services-sharjah"><strong>Sharjah</strong><small>Home, office & hourly cleaning →</small></a><a href="/cleaning-services-dubai"><strong>Dubai</strong><small>Explore local cleaning options →</small></a></div></section>`;
}
export function bookingPage() {
  return `<section class="wrap booking-screen"><span class="eyebrow">Choose · Schedule · Book</span><h1>Book your clean.</h1><p>Your service, time and address — all in one place.</p><form id="online-booking" class="planner"><div id="booking-connection" role="status">Loading the available services…</div><div class="field-grid"><label class="field wide">Service & duration<select name="service_id" required disabled><option value="">Connecting service catalogue…</option></select></label><div class="booking-price wide"><span>Service price <small>Tax and deposit details are confirmed by the team.</small></span><output id="booking-price" aria-live="polite">—</output></div><label class="field">City<select name="city"><option>Sharjah</option><option>Dubai</option></select></label><label class="field">Neighbourhood<input name="area" required maxlength="100" placeholder="e.g. Al Majaz or Al Barsha"></label><label class="field">Date<input type="date" name="date" required></label><label class="field">Time · UAE<input type="time" name="time" required></label><div class="wide" id="booking-slots" aria-live="polite"></div><label class="field wide">Full name<input name="customer_name" required maxlength="120" autocomplete="name"></label><label class="field wide">Mobile number<input name="customer_phone" type="tel" required maxlength="24" autocomplete="tel" placeholder="+971"></label><label class="field wide">Address & access instructions<input name="address_line" required maxlength="300" autocomplete="street-address" placeholder="Building / villa, street and apartment"></label></div><p class="fine">Recommended times are subject to availability when you submit. The team confirms location coverage, access and any additional requirements. <a href="/privacy">Privacy notice</a>.</p><button id="booking-submit" class="button pink" type="submit" disabled>Book cleaning</button><p id="booking-feedback" role="status" aria-live="polite"></p></form><div class="booking-fallback"><p>Prefer to discuss your cleaning needs?</p><a class="button outline" href="${DANFE_WHATSAPP}">Talk to us on WhatsApp</a></div></section>`;
}
export function bookingsPage() {
  return `<section class="wrap booking-screen"><span class="eyebrow">Your booking, up to date</span><h1>My bookings.</h1><p>Open the private link received after booking, or use a link shared by our team. Links expire after seven days.</p><div id="booking-list" aria-live="polite"><div class="location-box"><h2>No booking open yet.</h2><p>Bookings made in this browser tab appear here. For a booking made by the team, ask them for your private booking link.</p><a class="button pink" href="/book">Book a clean</a></div></div><form id="booking-change" class="planner" hidden><h2>Request a change</h2><label class="field">What would you like to change?<select name="kind"><option value="reschedule">Reschedule</option><option value="cancel">Cancel</option></select></label><label class="field">Preferred date & time · UAE<input type="datetime-local" name="preferred_start"></label><label class="field">Reason<input name="reason" required maxlength="500"></label><p class="fine">Changes need the team’s confirmation. Your existing booking remains active until confirmed. Cancellation terms may apply.</p><button class="button outline" type="submit">Send change request</button><p id="change-feedback" role="status"></p></form><div class="booking-fallback"><a class="button outline" href="${DANFE_WHATSAPP}">Contact the team</a><button class="button outline" type="button" id="forget-bookings">Clear bookings from this tab</button></div></section>`;
}
export function appNavigation(path: string) {
  const items = [{ path: '/', label: 'Home', icon: '⌂' }, { path: '/book', label: 'Book', icon: '✦' }, { path: '/bookings', label: 'Bookings', icon: '▣' }, { path: '/contact', label: 'Help', icon: '?' }];
  return `<nav class="app-tabs" aria-label="Mobile app navigation">${items.map(item => `<a href="${item.path}"${path === item.path ? ' aria-current="page"' : ''}><span aria-hidden="true">${item.icon}</span>${item.label}</a>`).join('')}</nav>`;
}
