export const DANFE_ORIGIN = 'https://www.danfecleaning.com';
export const DANFE_NAME = 'Our Danfe Cleaning Company';
export const DANFE_PHONE = '+971 56 214 5676';
export const DANFE_WHATSAPP = 'https://wa.me/971562145676';

export const services = [
  { slug: 'home-cleaning-sharjah', name: 'Home cleaning', tag: 'A little everyday ease', description: 'Hourly cleaning for apartments and villas in Sharjah, with your priorities guiding the visit.', intro: 'Give your home a fresh start without giving up your day. Tell us which rooms need attention and choose cleaning with your own supplies or with materials included.', tasks: ['Dusting accessible surfaces and furniture', 'Vacuuming and mopping suitable floors', 'Cleaning kitchen surfaces and bathroom fixtures', 'Tidying the rooms you want us to focus on'], note: 'Share your property size, room count and priorities so we can recommend the time needed. High-access work and specialist treatments should be discussed before the visit.' },
  { slug: 'office-cleaning-sharjah', name: 'Office cleaning', tag: 'Make room for good work', description: 'Cleaning enquiries for workplaces, shared spaces and offices. Plan a visit around your team.', intro: 'A clean workspace helps the day run smoothly. Discuss your office layout, access arrangements and preferred timing with our Sharjah team for a practical cleaning plan.', tasks: ['Accessible desks and common surfaces', 'Reception and shared areas', 'Suitable floors and walkways', 'Pantry and washroom cleaning'], note: 'Tell us about access rules, sensitive equipment and the number of workstations. Contract schedules and commercial scope are confirmed directly with the team.' },
  { slug: 'deep-cleaning-sharjah', name: 'Deep cleaning', tag: 'For the details that need more', description: 'Discuss a more thorough clean for built-up dust and the spaces that need extra attention.', intro: 'Some spaces need more than a regular refresh. Describe the condition of your home and the areas you would like us to tackle so we can discuss an appropriate deep-cleaning scope.', tasks: ['Detailed attention to accessible surfaces', 'Kitchen and bathroom cleaning priorities', 'Accessible corners and frequently missed areas', 'A room-by-room plan agreed before work begins'], note: 'Deep cleaning is quoted after discussing the scope. The hourly rates shown on this website are for normal hourly cleaning; specialist equipment and treatments are not automatically included.' },
  { slug: 'move-in-move-out-cleaning-sharjah', name: 'Move-in & move-out cleaning', tag: 'A fresh chapter starts here', description: 'Plan a clean for an empty apartment or villa before moving in or handing back the keys.', intro: 'Make your next move feel easier. Share whether the property is empty or furnished, its size, and your handover date so our team can discuss a suitable cleaning visit.', tasks: ['Cleaning accessible rooms and surfaces', 'Kitchen and bathroom priorities', 'Vacuuming and mopping suitable floors', 'An agreed checklist for your moving date'], note: 'Availability, cleaning time and any handover-specific requirements must be confirmed with our team. Cleaning does not guarantee a landlord inspection outcome.' },
] as const;

export const faqs = [
  { question: 'How much does hourly cleaning cost in Sharjah?', answer: 'Normal hourly cleaning is AED 25 per hour. Cleaning with materials is AED 35 per hour. Tell us your property size, cleaning priorities and preferred duration so we can confirm the total and availability before booking.' },
  { question: 'What is the difference between the two hourly options?', answer: 'With normal hourly cleaning, you provide the cleaning materials. The AED 35 per hour option includes materials. Please confirm any specific equipment or product requirements with our team before your visit.' },
  { question: 'Can I arrange recurring or contract cleaning?', answer: 'Yes, you can enquire about hourly and contractual cleaning, as advertised in our company flyer. Contact our team to discuss the frequency, scope and scheduling.' },
  { question: 'Can I book cleaning in both Sharjah and Dubai?', answer: 'Yes, select Sharjah or Dubai in the booking screen and share your exact neighbourhood and address. Our company is based in Sharjah, UAE, and the team confirms location coverage and scheduling for your visit. Contact us about other emirates.' },
  { question: 'Are deep cleaning and move-out cleaning charged at the same rate?', answer: 'The displayed AED 25 and AED 35 rates apply to normal hourly cleaning. Deep cleaning, move-out work and other specialist requests are assessed according to the property and agreed scope.' },
  { question: 'How do I book a cleaning visit?', answer: 'Use the enquiry planner or contact us on WhatsApp with your service, location, preferred date and hours. Our team will confirm availability, the work scope and the final price. An enquiry is not a confirmed booking.' },
];

export const pages = [
  { path: '/', title: 'Cleaning in Sharjah & Dubai | AED 25/hr | Our Danfe', description: 'Book Our Danfe cleaning in Sharjah and Dubai. Normal hourly cleaning AED 25/hr or AED 35/hr with materials. Home, office and specialist cleaning enquiries.' },
  ...services.map(service => ({ path: `/services/${service.slug}`, title: `${service.name} in Sharjah | Our Danfe Cleaning`, description: `${service.description} Contact Our Danfe Cleaning Company in Sharjah, UAE to confirm your cleaning scope, price and availability.` })),
  ...services.map(service => ({ path: `/services/${service.slug.replace('sharjah', 'dubai')}`, title: `${service.name} in Dubai | Our Danfe Cleaning`, description: `Arrange ${service.name.toLowerCase()} in Dubai with Our Danfe. Discuss apartment, villa or workplace access, cleaning priorities, location coverage and a suitable cleaning plan.` })),
  { path: '/cleaning-services-dubai', title: 'Cleaning Services in Dubai | Home & Office | Our Danfe', description: 'Book home and office cleaning in Dubai with Our Danfe. AED 25/hr normal cleaning or AED 35/hr with materials. Confirm coverage for your Dubai neighbourhood.' },
  { path: '/book', title: 'Book Cleaning in Sharjah & Dubai | Our Danfe', description: 'Choose your cleaning service, duration and preferred UAE time. Book with Our Danfe for Sharjah and Dubai through the connected ServBazaar service catalogue.' },
  { path: '/bookings', title: 'My Cleaning Bookings | Our Danfe', description: 'View your Our Danfe cleaning booking status, invoice updates and send a change request using your private booking link.', private: true },
  { path: '/cleaning-services-sharjah', title: 'Cleaning Services in Sharjah, UAE | Our Danfe', description: 'Arrange cleaning in Sharjah with Our Danfe. Enquire about apartments, villas and offices, hourly or contractual cleaning, and confirm availability for your location.' },
  { path: '/contact', title: 'Contact Our Danfe Cleaning Company | Sharjah, UAE', description: 'Contact Our Danfe Cleaning Company in Sharjah, UAE. Call +971 56 214 5676 or send a WhatsApp enquiry for hourly cleaning at AED 25 or AED 35 with materials.' },
  { path: '/privacy', title: 'Privacy Notice | Our Danfe Cleaning Company', description: 'How the Our Danfe Cleaning Company website handles your cleaning enquiries and contact information.' },
];
